"""
Train standalone meta-value network on offline dataset.

This utility performs pure supervised learning to test whether the meta-value
architecture can learn parameter quality given clean labels.

Trains on offline dataset (generated by build_meta_value_dataset.py) and reports:
- Training/validation loss curves
- Correlation on validation set
- Comparison to baselines (constant predictor, linear regression)

Usage:
    python -m src.analysis.train_offline_meta_value --dataset meta_value_dataset.pt
    python -m src.analysis.train_offline_meta_value --dataset meta_value_dataset.pt --epochs 500 --lr 0.001

Output:
    - Training curves plot
    - Final validation correlation
    - Comparison to baselines
"""

import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from typing import Dict, Tuple
from sklearn.linear_model import LinearRegression

from ..models.gradient_world_model import MetaValueNetwork


def load_dataset(path: Path) -> Dict:
    """Load offline meta-value dataset."""
    if not path.exists():
        raise FileNotFoundError(f"Dataset not found: {path}")
    return torch.load(path)


def split_dataset(
    parameters: torch.Tensor,
    avg_rewards: torch.Tensor,
    train_ratio: float = 0.8,
    seed: int = 42
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
    """
    Split dataset into train/validation.

    Args:
        parameters: Parameter tensors (N, n_arms)
        avg_rewards: Target rewards (N,)
        train_ratio: Fraction for training
        seed: Random seed

    Returns:
        (train_params, train_rewards, val_params, val_rewards)
    """
    torch.manual_seed(seed)
    n = len(parameters)
    indices = torch.randperm(n)

    n_train = int(n * train_ratio)

    train_idx = indices[:n_train]
    val_idx = indices[n_train:]

    return (
        parameters[train_idx],
        avg_rewards[train_idx],
        parameters[val_idx],
        avg_rewards[val_idx]
    )


def normalize_targets(
    train_rewards: torch.Tensor,
    val_rewards: torch.Tensor
) -> Tuple[torch.Tensor, torch.Tensor, float, float]:
    """
    Normalize rewards using training set statistics.

    Args:
        train_rewards: Training targets
        val_rewards: Validation targets

    Returns:
        (train_normalized, val_normalized, mean, std)
    """
    mean = train_rewards.mean().item()
    std = train_rewards.std().item()

    train_normalized = (train_rewards - mean) / (std + 1e-8)
    val_normalized = (val_rewards - mean) / (std + 1e-8)

    return train_normalized, val_normalized, mean, std


def train_meta_value(
    train_params: torch.Tensor,
    train_rewards: torch.Tensor,
    val_params: torch.Tensor,
    val_rewards: torch.Tensor,
    n_arms: int,
    hidden_dim: int = 32,
    epochs: int = 500,
    lr: float = 0.001,
    batch_size: int = 16
) -> Tuple[MetaValueNetwork, Dict]:
    """
    Train meta-value network on offline data.

    Args:
        train_params: Training parameters
        train_rewards: Training targets (normalized)
        val_params: Validation parameters
        val_rewards: Validation targets (normalized)
        n_arms: Number of arms
        hidden_dim: Hidden dimension
        epochs: Number of training epochs
        lr: Learning rate
        batch_size: Batch size

    Returns:
        (trained_network, metrics_dict)
    """
    # Initialize network
    meta_value = MetaValueNetwork(n_arms, hidden_dim)
    optimizer = torch.optim.Adam(meta_value.parameters(), lr=lr)

    # Metrics storage
    metrics = {
        'train_loss': [],
        'val_loss': [],
        'val_correlation': []
    }

    n_train = len(train_params)

    for epoch in range(epochs):
        # Training
        meta_value.train()
        epoch_loss = 0.0
        n_batches = 0

        # Shuffle training data
        indices = torch.randperm(n_train)
        for i in range(0, n_train, batch_size):
            batch_idx = indices[i:i+batch_size]
            if len(batch_idx) < 2:
                continue

            batch_params = train_params[batch_idx]
            batch_targets = train_rewards[batch_idx]

            # Forward pass
            predictions = meta_value(batch_params).squeeze()
            loss = F.mse_loss(predictions, batch_targets)

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        avg_train_loss = epoch_loss / max(n_batches, 1)
        metrics['train_loss'].append(avg_train_loss)

        # Validation
        meta_value.eval()
        with torch.no_grad():
            val_predictions = meta_value(val_params).squeeze()
            val_loss = F.mse_loss(val_predictions, val_rewards).item()
            metrics['val_loss'].append(val_loss)

            # Compute correlation
            if len(val_predictions) > 1:
                val_pred_np = val_predictions.numpy()
                val_target_np = val_rewards.numpy()

                if np.std(val_pred_np) > 1e-8 and np.std(val_target_np) > 1e-8:
                    corr = np.corrcoef(val_pred_np, val_target_np)[0, 1]
                else:
                    corr = 0.0
            else:
                corr = 0.0

            metrics['val_correlation'].append(corr)

        # Log progress
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch+1}/{epochs}: "
                  f"train_loss={avg_train_loss:.4f}, "
                  f"val_loss={val_loss:.4f}, "
                  f"val_corr={corr:.4f}")

    return meta_value, metrics


def evaluate_baselines(
    train_params: torch.Tensor,
    train_rewards: torch.Tensor,
    val_params: torch.Tensor,
    val_rewards: torch.Tensor
) -> Dict[str, float]:
    """
    Evaluate baseline predictors.

    Args:
        train_params: Training parameters
        train_rewards: Training targets (normalized)
        val_params: Validation parameters
        val_rewards: Validation targets (normalized)

    Returns:
        Dictionary of baseline correlations
    """
    results = {}

    # Baseline 1: Constant predictor (mean)
    constant_pred = torch.ones_like(val_rewards) * train_rewards.mean()
    if np.std(constant_pred.numpy()) > 1e-8 and np.std(val_rewards.numpy()) > 1e-8:
        results['constant'] = np.corrcoef(
            constant_pred.numpy(),
            val_rewards.numpy()
        )[0, 1]
    else:
        results['constant'] = 0.0

    # Baseline 2: Linear regression on parameters
    lr_model = LinearRegression()
    lr_model.fit(train_params.numpy(), train_rewards.numpy())
    lr_pred = lr_model.predict(val_params.numpy())

    if np.std(lr_pred) > 1e-8 and np.std(val_rewards.numpy()) > 1e-8:
        results['linear_regression'] = np.corrcoef(
            lr_pred,
            val_rewards.numpy()
        )[0, 1]
    else:
        results['linear_regression'] = 0.0

    return results


def plot_results(metrics: Dict, output_path: Path):
    """Plot training curves."""
    fig, axes = plt.subplots(1, 3, figsize=(15, 4))

    # Training loss
    axes[0].plot(metrics['train_loss'], label='Train')
    axes[0].plot(metrics['val_loss'], label='Validation')
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('MSE Loss')
    axes[0].set_title('Training Curves')
    axes[0].legend()
    axes[0].grid(True, alpha=0.3)

    # Validation correlation
    axes[1].plot(metrics['val_correlation'])
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Correlation')
    axes[1].set_title('Validation Correlation Over Training')
    axes[1].grid(True, alpha=0.3)
    axes[1].axhline(y=0, color='k', linestyle='--', alpha=0.3)

    # Loss on log scale
    axes[2].semilogy(metrics['train_loss'], label='Train')
    axes[2].semilogy(metrics['val_loss'], label='Validation')
    axes[2].set_xlabel('Epoch')
    axes[2].set_ylabel('MSE Loss (log scale)')
    axes[2].set_title('Training Curves (Log Scale)')
    axes[2].legend()
    axes[2].grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig(output_path, dpi=150, bbox_inches='tight')
    print(f"Training curves saved to: {output_path}")


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Train standalone meta-value network on offline dataset"
    )
    parser.add_argument(
        '--dataset',
        type=Path,
        required=True,
        help='Path to offline dataset (e.g., meta_value_dataset.pt)'
    )
    parser.add_argument(
        '--epochs',
        type=int,
        default=500,
        help='Number of training epochs (default: 500)'
    )
    parser.add_argument(
        '--lr',
        type=float,
        default=0.001,
        help='Learning rate (default: 0.001)'
    )
    parser.add_argument(
        '--batch-size',
        type=int,
        default=16,
        help='Batch size (default: 16)'
    )
    parser.add_argument(
        '--hidden-dim',
        type=int,
        default=32,
        help='Hidden dimension (default: 32)'
    )
    parser.add_argument(
        '--train-ratio',
        type=float,
        default=0.8,
        help='Training set ratio (default: 0.8)'
    )
    parser.add_argument(
        '--output',
        type=Path,
        default=Path('offline_meta_value_training.png'),
        help='Output path for plots'
    )
    parser.add_argument(
        '--seed',
        type=int,
        default=42,
        help='Random seed (default: 42)'
    )

    args = parser.parse_args()

    # Load dataset
    print(f"Loading dataset: {args.dataset}")
    dataset = load_dataset(args.dataset)

    parameters = dataset['parameters']
    avg_rewards = dataset['avg_rewards']
    n_arms = dataset['metadata']['n_arms']

    print(f"\nDataset loaded:")
    print(f"  Samples: {len(parameters)}")
    print(f"  Arms: {n_arms}")
    print(f"  Reward range: [{avg_rewards.min():.3f}, {avg_rewards.max():.3f}]")
    print(f"  Reward mean: {avg_rewards.mean():.3f} ± {avg_rewards.std():.3f}")

    # Split dataset
    print(f"\nSplitting dataset (train ratio: {args.train_ratio})...")
    train_params, train_rewards, val_params, val_rewards = split_dataset(
        parameters, avg_rewards, args.train_ratio, args.seed
    )
    print(f"  Train: {len(train_params)} samples")
    print(f"  Validation: {len(val_params)} samples")

    # Normalize targets
    train_rewards_norm, val_rewards_norm, mean, std = normalize_targets(
        train_rewards, val_rewards
    )
    print(f"  Normalization: mean={mean:.3f}, std={std:.3f}")

    # Train meta-value network
    print(f"\nTraining meta-value network...")
    print(f"  Epochs: {args.epochs}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Batch size: {args.batch_size}")
    print(f"  Hidden dim: {args.hidden_dim}")

    meta_value, metrics = train_meta_value(
        train_params,
        train_rewards_norm,
        val_params,
        val_rewards_norm,
        n_arms,
        hidden_dim=args.hidden_dim,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size
    )

    # Final results
    final_corr = metrics['val_correlation'][-1]
    final_val_loss = metrics['val_loss'][-1]

    print(f"\nFinal Results:")
    print(f"  Validation loss: {final_val_loss:.4f}")
    print(f"  Validation correlation: {final_corr:.4f}")

    # Evaluate baselines
    print(f"\nBaseline comparisons:")
    baselines = evaluate_baselines(
        train_params, train_rewards_norm,
        val_params, val_rewards_norm
    )
    for name, corr in baselines.items():
        print(f"  {name}: {corr:.4f}")

    # Interpretation
    print(f"\nInterpretation:")
    if abs(final_corr) < 0.1:
        print("  POOR: Meta-value network shows almost no correlation.")
        print("  The architecture cannot learn from clean labels.")
    elif abs(final_corr) < 0.3:
        print("  WEAK: Meta-value shows weak correlation.")
        print("  Architecture can learn some signal but is limited.")
    elif abs(final_corr) < 0.5:
        print("  MODERATE: Meta-value shows moderate correlation.")
        print("  Architecture can learn reasonable signal from clean data.")
    else:
        print("  STRONG: Meta-value shows strong correlation.")
        print("  Architecture successfully learns parameter quality.")

    if final_corr < 0:
        print("  WARNING: Negative correlation suggests learning wrong signal.")

    # Compare to best baseline
    best_baseline = max(baselines.values())
    if final_corr > best_baseline + 0.05:
        print(f"  Meta-value outperforms baselines (improvement: {final_corr - best_baseline:.3f})")
    elif final_corr < best_baseline - 0.05:
        print(f"  Meta-value underperforms baselines (gap: {best_baseline - final_corr:.3f})")
    else:
        print(f"  Meta-value performs similar to baselines")

    # Plot results
    plot_results(metrics, args.output)


if __name__ == '__main__':
    main()
